# Generated by Django 4.2.7 on 2023-11-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='birthdate',
            field=models.DateField(verbose_name='Birthday'),
        ),
    ]
