# Generated by Django 4.2.7 on 2023-11-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_beneficiary_responsible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='Identification',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='Name',
            new_name='name',
        ),
    ]
