# Generated by Django 4.2.7 on 2023-11-21 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0004_rename_identification_beneficiary_identification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
    ]
